{
    'name': "Certificate Verification",
    'summary': """certificate verification of different courses""",
    'author': "ladn",
    'description': """certificate verification""",
    'sequence': -100,
    'version': '16.0.1.0.0',
    'depends': ['base', 'sale', 'account'],
    'data': [
        'data/certificate_sequence.xml',
        'data/partner_sequence.xml',
        'security/ir.model.access.csv',
        'reports/reports.xml',
        'reports/templates.xml',
        'views/certificate.xml',
        'views/certificate_course.xml',
        'views/certificate_partner.xml',
        'views/res_partner.xml',
        'views/certificate_menus.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
